services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: api
      TZ: UTC
    ports:
      - "3306:3306"
